CREATE DATABASE IF NOT EXISTS clouddb;
CREATE USER IF NOT EXISTS 'binam'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON clouddb.* TO 'binam'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '123123';