MYSQL_ROOT_PASSWORD: "123123"
MYSQL_DATABASE: "clouddb"
MYSQL_USER: "binam"
MYSQL_PASSWORD: "123"
PMA_HOST: "mariadb"
WP_URL: "http://binam.cloud.com.tr"
WP_TITLE: "Selam Cloud-1"
WP_ADMIN_LOGIN: "admin"
WP_ADMIN_PASSWORD: "123"
WP_ADMIN_EMAIL: "binam@cloud.tr"
WP_USER_LOGIN: "binam"
WP_USER_PASSWORD: "123"
WP_USER_EMAIL: "binam42@cloud.tr"
ansible_user: "binam"
docker_versiyonu: 1.29.2