---
- name: Setup Docker on Ubuntu Server 22.04
  hosts: all
  become: true
  remote_user: root
  roles:
    - config
    - docker
  tasks:
    - name: Copy cloud directory
      copy:
        src: ../../cloud/
        dest: /home/{{ ansible_user }}/cloud/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Copy Docker Compose file
      template:
        src: cloud/docker-compose.yaml.j2
        dest: /home/{{ ansible_user }}/cloud/docker-compose.yaml

    - name: Run Docker Compose
      shell: docker-compose -f /home/{{ ansible_user }}/cloud/docker-compose.yaml up -d
      args:
        chdir: /home/{{ ansible_user }}/cloud/