---
- name: Setup All Systems on AWS Server
  hosts: amazon_instances
  become: true
  remote_user: root
  roles:
    - role: config
      until: result is success
      retries: 3
      delay: 5
    - role: docker
      until: result is success
      retries: 3
      delay: 5
    - role: copy
      until: result is success
      retries: 3
      delay: 5
    - role: run
      until: result is success
      retries: 3
      delay: 5
