CREATE DATABASE IF NOT EXISTS clouddb;
CREATE USER IF NOT EXISTS 'dertops'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON clouddb.* TO 'dertops'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '123';